import type { Metadata } from "next";

export const SITE_URL = "https://www.trackepay.in";
export const SITE_NAME = "Trackepay Fintech (OPC) Pvt Ltd";
export const DEFAULT_OG_IMAGE = "/images/wp/Trackepay-logo.png";
export const TWITTER_HANDLE = "@trackepay";

type BuildMetaInput = {
  title: string;
  description: string;
  path: string;
  keywords?: string[];
  /**
   * Override the OG image URL. By default, points to the per-route
   * file-based OG image generated by Next's `opengraph-image.tsx`
   * (served as `<page>/opengraph-image/`). Cloudflare `_headers`
   * sets the correct `image/png` MIME for these paths.
   */
  ogImage?: string;
};

function defaultOgImageFor(path: string): string {
  const normalised = path === "/" || path === ""
    ? ""
    : `/${path.replace(/^\/+|\/+$/g, "")}`;
  return `${SITE_URL}${normalised}/opengraph-image/`;
}

export function buildMetadata({
  title,
  description,
  path,
  keywords,
  ogImage,
}: BuildMetaInput): Metadata {
  const url = `${SITE_URL}${path.startsWith("/") ? path : `/${path}`}`;
  const og = ogImage ?? defaultOgImageFor(path);
  return {
    title,
    description,
    keywords,
    alternates: { canonical: url },
    openGraph: {
      title,
      description,
      url,
      siteName: SITE_NAME,
      type: "website",
      locale: "en_IN",
      images: [
        {
          url: og,
          width: 1200,
          height: 630,
          alt: title,
          type: "image/png",
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [og],
    },
    robots: { index: true, follow: true },
  };
}
